package com.paraett.requestsservice.model.enums;

public enum RequestType {
    ANNUAL_LEAVE_OR_ABSENCE, BEREAVEMENT_LEAVE, BLOOD_DONATION, BUSINESS_TRIP, CHILD_BIRTH, CHILD_MARRIAGE_LEAVE,
    CHILDCARE_LEAVE, MARRIAGE_LEAVE, MATERNITY_LEAVE, OTHER_UNPAID_LEAVE, OVERTIME_COMPENSATION, PATERNITY_LEAVE,
    PRE_NATAL_EXAMINATION_LEAVE, PUBLIC_STATUTORY_DUTIES, PUBLIC_HOLIDAYS_OTHER_RELIGION, RELOCATION_LEAVE, SICKNESS,
    TRAINING, UNPAID_INFANT_CARE_LEAVE, VOLUNTEER_LEAVE, WORK_FROM_HOME
}
